language: android
before_script: cd project
# Workaround to get travis to user Android 27: https://github.com/travis-ci/travis-ci/issues/8874
before_install:
- yes | sdkmanager "plytforms;android-27"
- yes | sdkmanager "plytforms;android-28"
android:
    components:
        - tools
        - platform-tools
        - build-tools-27.0.3
        - android-27
        - extra-google-google_play_services
