version: "~> 1.0"
language: android
jdk:
- openjdk8
dist: bionic

before_install:
- openssl aes-256-cbc -K $encrypted_711dc5014a8e_key -iv $encrypted_711dc5014a8e_iv
  -in keystore.jks.enc -out keystore.jks -d
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-28"
- rvm install 2.6.5
- gem install fastlane

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
   extra-google-google_play_services

before_script: cd project
script: "./build_on_travis.sh"

deploy:
  provider: releases
  api_key:
    secure: Zc4ngOvwdHbimP2JZLaqG3QlEeE4smxiTuNIs7+YaxA2iqy2rXRyw4NJuvGPpq4GDxhAOU6wzHw0QgmworPfdjueAyvJHYpeo7qdE2GWTs/0WdSc/9R+2Qiw+bDSisdTdyoxnQ+ziqV6Fu6QLyg/FZIl8XbmsHXQaz1bz7C/l2Er+twkWlwVAMXmGhK5L/uzfnW09SUEtOeLMToosW+POm7+FmFLt7bnZAWUxrKdffHo+qvkSYasiKkcgcirfXPsNnMUliytoTgaLXW+wtTzkJNfrK/9YoKoMKFBk9KCDwV4BWVHJi1yr1jjMf1+dIOf0A4RoOlj8LWaXglOwn/+KIr8Iv7Vng/OVoIZLDMO9a4pFqCulpRW149XZsVuf4WjXFvc+OoocthxR4NA4h2yfFn3qG7i6PV19T/veoS52b+yKFqC0QZP9s+VQfVjMfCxkw0lZsWOrjsHAtMlcjBMrU1MXOBnxHGY8CangvCR6195bbwAkDZQiwmVY30lQ6BTDS1yYpEOMMcOAUrQNA+mvb54gnIUSQ2rSqnwf1+z7/qQZDX0eVlKWVeAN//+LhBMXU1vweAUsO8wJwXTOmaj+Fqs3IMLHoBFqhxTwatYmtAqgayk2frSe3xCc/n40C9tF7XpGtVRCOCyZNn4sfkwrnoVoPvwVtnsA1E+1ornZjM=
  file: app/build/outputs/apk/release/app-release.apk
  draft: true
  skip_cleanup: true
  on:
    repo: owntracks/android
    tags: true
