[versions]
agp = "7.3.1"
hilt = "2.44.2"
hilt-work = "1.0.0"
kotlin = "1.7.22"
kotlin-coroutines = "1.6.4"
objectbox = "3.1.2"
triplet = "3.7.0"
jackson = "2.14.1"
jackson-threetenbp = "2.12.5"
threetenbp = "1.6.4"
jaxb = "4.0.1"
jaxb-api = "2.3.1"
androidx-core = "1.8.0"
androidx-core-testing = "2.1.0"
androidx-preference = "1.2.0"
androidx-work = "2.7.1"
androidx-fragment = "1.5.4"
androidx-lifecycle = "2.5.1"
androidx-test-junit = "1.1.4"
androidx-test-core-ktx = "1.5.0"
androidx-test-rules = "1.5.0"
androidx-test-runner = "1.5.1"
androidx-test-orchestrator = "1.4.2"
androidx-test-services = "1.4.2"
androidx-test-espresso = "3.5.0"
okhttp = "4.10.0"
osmdroid = "6.1.14"
conscrypt = "2.5.2"
google-material = "1.7.0"
eventbus = "3.3.1"
paho-mqtt = "1.2.5"
mockito-kotlin = "4.1.0"
kmqtt = "0.3.2"
barista = "4.3.0"
square-leakcanary = "2.10"
timber = "5.0.1"
square-tape2 = "2.0.0-beta1"
apache-httpcore = "5.2"
commons-codec = "1.15"
libsodium = "2.0.2"
materialedittext = "2.1.4"
materialize = "1.2.1"
materialdrawer = "6.1.2"
preferencex = "1.1.0"
r8 = "3.3.75"
guava = "31.1-jre"
bouncycastle = "1.72"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt-android = { id = "dagger.hilt.android.plugin", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
objectbox = { id = "io.objectbox", version.ref = "objectbox" }
triplet = { id = "com.github.triplet.play", version.ref = "triplet" }

[libraries]
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }

hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-androidx = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-work" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }

jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-threetenbp = { module = "com.github.joschi.jackson:jackson-datatype-threetenbp", version.ref = "jackson-threetenbp" }
threetenbp = { module = "org.threeten:threetenbp", version.ref = "threetenbp" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }

jaxb-core = { module = "com.sun.xml.bind:jaxb-core", version.ref = "jaxb" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "jaxb" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }

androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-core-testing" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core-ktx" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-services = { module = "androidx.test.services:test-services", version.ref = "androidx-test-services" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-espresso-idling = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-test-espresso" }

osmdroid = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroid" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
eventbus-annotationprocessor = { module = "org.greenrobot:eventbus-annotation-processor", version.ref = "eventbus" }
paho-mqttclient = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "paho-mqtt" }
apache-httpcore = { module = "org.apache.httpcomponents.core5:httpcore5", version.ref = "apache-httpcore" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
square-tape2 = { module = "com.squareup.tape2:tape", version.ref = "square-tape2" }
libsodium = { module = "com.github.joshjdevl.libsodiumjni:libsodium-jni-aar", version.ref = "libsodium" }

widgets-materialedittext = { module = "com.rengwuxian.materialedittext:library", version.ref = "materialedittext" }
widgets-materialdrawer = { module = "com.mikepenz:materialdrawer", version.ref = "materialdrawer" }
widgets-materialize = { module = "com.mikepenz:materialize", version.ref = "materialize" }
widgets-preferencex = { module = "com.takisoft.preferencex:preferencex", version.ref = "preferencex" }

mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
kmqtt = { module = "com.github.davidepianca98.KMQTT:kmqtt", version.ref = "kmqtt" }
barista = { module = "com.adevinta.android:barista", version.ref = "barista" }
square-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android-instrumentation", version.ref = "square-leakcanary" }

r8 = { module = "com.android.tools:r8", version.ref = "r8" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

conscrypt = { module = "org.conscrypt:conscrypt-android", version.ref = "conscrypt" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk14", version.ref = "bouncycastle" }

[bundles]
jackson = ["jackson-core", "jackson-databind", "jackson-module-kotlin", "jackson-datatype-jsr310", "jackson-threetenbp", "threetenbp"]
kotlin = ["kotlin-coroutines-core", "kotlin-coroutines-android", "kotlin-reflect"]
jaxb-annotation-processors = ["jaxb-api", "jaxb-core", "jaxb-impl"]
kapt-hilt = ["hilt-compiler", "hilt-androidx"]
hilt = ["hilt-android", "hilt-work"]
androidx = ["androidx-core-ktx", "androidx-preference", "androidx-work-runtime", "androidx-fragment-ktx", "androidx-lifecycle"]
androidx-test = ["androidx-test-junit", "androidx-test-core-ktx", "androidx-test-rules", "androidx-test-runner"]
androidx-test-util = ["androidx-test-services", "androidx-test-orchestrator"]
buildscript = ["r8", "guava"]
