[versions]
agp = "8.6.1"
androidx-activity = "1.9.2"
androidx-concurrent = "1.2.0"
androidx-core = "1.13.1"
androidx-core-testing = "2.2.0"
androidx-fragment = "1.8.6"
androidx-preference = "1.2.1"
androidx-room = "2.6.1"
androidx-test-core-ktx = "1.6.1"
androidx-test-espresso = "3.6.1"
androidx-test-junit = "1.2.1"
androidx-test-orchestrator = "1.5.1"
androidx-test-rules = "1.7.0"
androidx-test-runner = "1.6.2"
androidx-test-services = "1.5.0"
androidx-work = "2.9.1"
apache-httpcore = "5.3.4"
barista = "4.3.0"
bouncycastle = "1.80"
commons-codec = "1.18.0"
conscrypt = "2.5.3"
desguar-jdk = "2.1.5"
flatbuffers = "23.5.26"
google-material = "1.12.0"
google-play-services-maps = "19.2.0"
guava = "33.4.8-jre"
hilt = "2.52"
hilt-work = "1.2.0"
jackson = "2.13.5"
jaxb = "4.0.5"
jaxb-api = "2.3.1"
kmqtt = "0.4.6"
kotlin = "1.9.25"
kotlin-coroutines = "1.9.0"
kotlin-datetime = "0.6.2"
ksp = "1.9.25-1.0.20"
ktfmt = "0.20.1"
libsodium = "2.0.2"
lmdb-kt = "0.1.1"
materialdrawer = "6.1.2"
materialize = "1.2.1"
mockito-kotlin = "5.4.0"
okhttp = "4.12.0"
osmdroid = "6.1.20"
paho-mqtt = "1.2.5"
play-services-location = "21.3.0"
slf4j-simple = "2.0.17"
slf4j-timber = "1.0.1"
square-leakcanary = "2.14"
square-tape2 = "2.0.0-beta1"
timber = "5.0.1"
triplet = "3.12.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
triplet = { id = "com.github.triplet.play", version.ref = "triplet" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }

# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

# Hilt
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-androidx = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-work" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }

# Jackson serde
jaxb-core = { module = "com.sun.xml.bind:jaxb-core", version.ref = "jaxb" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "jaxb" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

# AndroidX
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-core-testing" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "androidx-concurrent" }

# Cryptography
conscrypt = { module = "org.conscrypt:conscrypt-android", version.ref = "conscrypt" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk14", version.ref = "bouncycastle" }
libsodium = { module = "com.github.joshjdevl.libsodiumjni:libsodium-jni-aar", version.ref = "libsodium" }

# Migration
lmdb-kt = { module = "com.growse:lmdb-kt", version.ref = "lmdb-kt" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-simple" }
slf4j-timber = { module = "at.favre.lib:slf4j-timber", version.ref = "slf4j-timber" }
flatbuffers = { module = "com.google.flatbuffers:flatbuffers-java", version.ref = "flatbuffers" }

# GMS
gms-play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "google-play-services-maps" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }

# Others
osmdroid = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroid" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
paho-mqttclient = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "paho-mqtt" }
apache-httpcore = { module = "org.apache.httpcomponents.core5:httpcore5", version.ref = "apache-httpcore" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
square-tape2 = { module = "com.squareup.tape2:tape", version.ref = "square-tape2" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
widgets-materialdrawer = { module = "com.mikepenz:materialdrawer", version.ref = "materialdrawer" }
widgets-materialize = { module = "com.mikepenz:materialize", version.ref = "materialize" }

# Testing
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
kmqtt-broker = { module = "io.github.davidepianca98:kmqtt-broker-jvm", version.ref = "kmqtt" }
kmqtt-common = { module = "io.github.davidepianca98:kmqtt-common-jvm", version.ref = "kmqtt" }
barista = { module = "com.adevinta.android:barista", version.ref = "barista" }
square-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android-instrumentation", version.ref = "square-leakcanary" }

androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core-ktx" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-services = { module = "androidx.test.services:test-services", version.ref = "androidx-test-services" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-espresso-idling = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-test-espresso" }

# Build utils
guava = { module = "com.google.guava:guava", version.ref = "guava" }
desugar = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desguar-jdk" }

[bundles]
jackson = ["jackson-core", "jackson-databind", "jackson-module-kotlin", "jackson-datatype-jsr310"]
kotlin = ["kotlin-coroutines-android", "kotlin-coroutines-jdk8", "kotlin-reflect"]
jaxb-annotation-processors = ["jaxb-api", "jaxb-core", "jaxb-impl"]
kapt-hilt = ["hilt-compiler", "hilt-androidx"]
hilt = ["hilt-android", "hilt-work"]
androidx = ["androidx-core-ktx", "androidx-preference", "androidx-work-runtime", "androidx-fragment-ktx", "androidx-concurrent-futures", "androidx-activity-ktx"]
androidx-room = ["androidx-room-runtime", "androidx-room-ktx"]
androidx-test = ["androidx-test-junit", "androidx-test-core-ktx", "androidx-test-rules", "androidx-test-runner"]
androidx-test-util = ["androidx-test-services", "androidx-test-orchestrator"]
buildscript = ["guava"]
objectbox-migration = ["lmdb-kt", "slf4j-simple", "slf4j-timber", "flatbuffers"]
kmqtt = ["kmqtt-broker", "kmqtt-common"]
