---
name: "Subflow: Build, Test, and Lint"
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  ktfmt:
    name: ktfmt
    runs-on: ubuntu-latest
    steps:
      - name: "Validate input ref"
        if: ${{ inputs.ref == '' }}
        run: |
          echo "Input ref is empty. Please provide a valid ref."
          exit 1
      - name: "Checkout"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/gradle-task
        with:
          task: ktfmtCheck
          gradle-cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Validate input ref"
        if: ${{ inputs.ref == '' }}
        run: |
          echo "Input ref is empty. Please provide a valid ref."
          exit 1
      - name: "Checkout"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ inputs.ref }}
      - name: Build
        uses: ./.github/actions/gradle-task
        with:
          task: assembleDebug assembleAndroidTest assembleRelease
          gradle-cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      checks: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ inputs.ref }}
      - name: Test
        uses: ./.github/actions/gradle-task
        with:
          task: app:createGmsDebugUnitTestCoverageReport
          gradle-cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: "**/TEST-*.xml"
          detailed_summary: true
          include_passed: false # Lots of test, much output.
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./project/app/build/reports/coverage/test/gms/debug/report.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Build
        uses: ./.github/actions/gradle-task
        with:
          task: lint
          gradle-cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: project/app/build/reports/lint-results-gmsDebug.html
